import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { useEffect } from 'react';
import AccountService from '../utils/services/Account.service';
import axios from 'axios';
import { useRouter } from 'next/router';
import AuthService from '../utils/services/Auth.service';
import { useMutation } from '@tanstack/react-query';

export default function Dashboard() {
  const router = useRouter();
  const { mutate } = useMutation(AuthService.signOut, {
    onSuccess: () => {
      router.push('/login');
    }
  });

  useEffect(() => {
    const getAccounts = async () => {
      try {
        const { data } = await AccountService.getList();
        console.log(data);
      } catch (error) {
        if (axios.isAxiosError(error)) {
          const response = error.response;
          const status = response ? response.status : 400;

          if (status === 401) {
            router.push('/login');
            return;
          }
        }
      }
    };

    getAccounts();
  }, [router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Link href='/test'>테스트로</Link>
        <button onClick={() => mutate()}>로그아웃</button>
      </main>
    </div>
  );
}
