import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAppDispatch, useAppSelector } from '../utils/store';
import { setUser } from '../utils/store/userReducer';
import LocalService from '../utils/services/Local.service';
import { useEffect } from 'react';
import CookieService from '../utils/services/Cookie.service';

import { Container } from '@mui/material';
import LoginForm from '../components/LoginForm';

export default function Login() {
  const dispatch = useAppDispatch();
  const state = useAppSelector((state) => state.user);

  useEffect(() => {
    if (state) {
      dispatch(setUser(null));
    }

    CookieService.remove('expiredDate');
    LocalService.remove('userId');
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container
          sx={{
            height: '100vh',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}
        >
          <LoginForm />
        </Container>
      </main>
    </div>
  );
}
