import Head from 'next/head';
import Link from 'next/link';
import { useEffect } from 'react';
import AccountService from '../../utils/services/Account.service';
import axios from 'axios';
import { useRouter } from 'next/router';
import AuthService from '../../utils/services/Auth.service';
import { useMutation } from '@tanstack/react-query';
import Layout from '../../components/Layout';

export default function Accounts() {
  const router = useRouter();
  const { mutate } = useMutation(AuthService.signOut, {
    onSuccess: () => {
      router.push('/login');
    }
  });

  useEffect(() => {
    const getAccounts = async () => {
      try {
        const { data } = await AccountService.getList();
        console.log(data);
      } catch (error) {
        if (axios.isAxiosError(error)) {
          const response = error.response;
          const status = response ? response.status : 400;

          if (status === 401) {
            router.push('/login');
            return;
          }
        }
      }
    };

    getAccounts();
  }, [router]);

  return (
    <article>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Layout title='계좌 목록'>
          <Link href='/test'>테스트로</Link>
          <button onClick={() => mutate()}>로그아웃</button>
        </Layout>
      </main>
    </article>
  );
}
