import Head from 'next/head';
import Layout from '../../components/Layout';

export default function Users() {
  return (
    <article>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Layout title='사용자'>
          <h1>유저 리스트</h1>
        </Layout>
      </main>
    </article>
  );
}
